version: '3.9'

services:
  db:
    image: mysql
    restart: always
    shm_size: 128mb
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: alfamaweb
      MYSQL_DATABASE: alfama-db
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .  # Caminho para o Dockerfile
    ports:
      - "8080:8080"  # Mapeia a porta 8080 do contêiner para a porta 8080 do host
    volumes:
      - .:/var/www/html
    depends_on:
      - db

volumes:
  mysql_data:
