version: '3.9'

services:
  db:
    image: mysql
    restart: always
    shm_size: 128mb
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: alfamaweb
      MYSQL_DATABASE: alfama-db
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    #   - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
