CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(20),
  cpf VARCHAR(14) UNIQUE,
  company VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  address TEXT
);
